### ISSUE TITLE
working with recursively stored spatial data

### ISSUE THREAD

**Issue by mdsumner** [jennybc/repurrrsive#1]
Your call for examples made me realize I need purrr for table-fying the new `sf` classes. 

Warning, this is not extensively tested, and I only look at polygons below (not lines or multi-points), but I think a purrr/dplyr-friendly illustration to open up the fortify black box is worth exploring. 

In sp, data are stored as a list of list of matrices, and ggplot2 has `fortify` methods to convert it to long table form. 

``` R
library(sp)
library(rgdal)
library(raster)
spdf <- shapefile(system.file("shapes/sids.shp", package="maptools"))

library(ggplot2)
ff <- fortify(spdf)
ggplot(ff) + aes(x = long, y = lat, group = group, fill = id) + geom_polygon() + geom_path() + guides(fill = FALSE)
```

The underlying `ggplot2:::fortify.Polygons` method, applied by `ggplot2:::fortify.SpatialPolygons` and `ggplot2:::fortify.SpatialPolygonsDataFrame` is a bit obscure. 

We can achieve the same with purrr mapping (though we get slightly different fill due to the changed ID sorting). 

``` R
library(purrr)
 pm <- bind_rows(map(spdf@polygons, function(x) bind_rows(map(x@Polygons, function(y) as.data.frame(y@coords)), .id = "part")), .id = "feature")
## part must be unique
pm <- pm %>% mutate(part = paste(part, feature, sep = "-"))
ggplot(pm) + aes(x = V1, y = V2, group = part, fill = feature) + geom_polygon() + geom_path() +  guides(fill = FALSE)
```

We can apply a similar approach to the new `sf` classes, and it's a fair bit simpler. 

``` R
library(sf)  ## new!  on CRAN

## more or less the same dataset
nc <- st_read(system.file("gpkg/nc.gpkg", package="sf"), "nc.gpkg", crs = 4267)
nc_geom_long <- bind_rows(map(nc$geom, function(x) bind_rows(map(x, as.data.frame), .id = "part")), .id = "feature")
## part must be unique
nc_geom_long <- nc_geom_long %>% mutate(part = paste(part, feature, sep = "-"))
## here the names are X1/X2 rather than V1/V2 but it's not really relevant
ggplot(nc_geom_long) +  aes(x = X1, y = X2, group = part, fill = feature) + geom_polygon() + geom_path() +  guides(fill = FALSE)


```

**Comment by jennybc** [comment]
I've just come through here doing upkeep and issue triage and it feels like the time to just close this one. All the relevant packages and domains have progressed quite a bit since 2016.
