### ISSUE TITLE
Data source idea: StarWars API

### ISSUE THREAD

**Issue by jennybc** [jennybc/repurrrsive#3]
also via @masalmon

https://swapi.co

**Comment by cwickham** [comment]
Would you open to me adding the star wars lists from my purrr tutorial? I.e. the lists created here:
https://github.com/cwickham/purrr-tutorial/blob/master/code/swapi.R  (probably with a `sw_` prefix added to their names).

**Comment by jennybc** [comment]
That would be great! Will you also add the acquisition and munging code to data-raw?

**Comment by cwickham** [comment]
Yes, so the plan is:
1. Add acquisition and munging code to data-raw, that
2. adds `sw_characters`, `sw_films`, ... to the data directory (i.e. via `devtools::use_data()`)
3. Update readme to include some details about `sw_` objects

Should I also provide xml and json objects?  If yes, I'll just mimic whatever you did for the other data.

**Comment by jennybc** [comment]
Sounds good! You can basically follow the pattern you see for Game of Thrones and/or GitHub.

Whether you want the xml and json is in the package is up to you. If you think it will be helpful in future workshops or whatever, then feel free to add it. I think the lists are really the main point. But I needed some JSON and XML to use as demos in teaching, so I made it while I was here.
