### ISSUE TITLE
xpath intuitive on nested list tibbles?

### ISSUE THREAD

**Issue by timelyportfolio** [jennybc/repurrrsive#6]
Not sure where to put this, so I decided to file an issue here.  `xPath` in general scares and intimidates, but as I was playing with this [plotly + defiant.js example](http://bl.ocks.org/timelyportfolio/2c8e0fcbd5b4fb73151c1be9df17c103), I started to wonder if `xPath` on nested objects/`JSON` is more intuitive and visual.  See [defiant.js xpath evaluator](http://www.defiantjs.com/#xpath_evaluator) as an example.  If you agree, then I will explore potential ways of pursuing ways of incorporating this in `R`.

![xpath_json_defiant](https://cloud.githubusercontent.com/assets/837910/20571968/1f12c46a-b16f-11e6-8072-58fb3e57f815.gif)

**Comment by jennybc** [comment]
xmlview from @hrbrmstr is already in this space:

https://github.com/hrbrmstr/xmlview

But I also gather it may be stalled a bit? I totally agree that an interactive viewer is useful. xmlview does (or did) that and it's a nice way to see the effect of XPath expressions. The thing you show above seems more fully featured, though.

**Comment by timelyportfolio** [comment]
I don't think I was clear enough. This discussion is not about the view but is more for understanding how to query a nested tibble by using xpath syntax on json.  This is a very rough idea and more stream of consciousness.

**Comment by hrbrmstr** [comment]
The `xml_view()` functionality (w/o addressing the path searching issue @jennybc raised ;-) is exposed in the `htmltidy` pkg (in current CRAN version). @timelyportfolio's JSON viewer seemed fully featured enough to not try to add one more thing like it to CRAN.

@timelyportfolio => so, you're suggesting something like (replying in e-mail so I'll fix in the GH editor if this is borked):

```
incredibly_wickedly_nested_list %>%
  map_query(".//book[@price > 20]")
```

to return a list of `book`s that meet said criteria, with the general rule being atomic values are attributes and everything else is a node?

Writing said XPath subset parser in R wld be kinda "ugh" but much more doable (and faster) with C++ (perhaps borrowing the parser core from https://github.com/korczis/tinyxpath).

**Comment by timelyportfolio** [comment]
@hrbrmstr, not sure I'm suggesting a new ambitious project, but it does seem that tree/nested hierarchy query engines in any library are very weak/nonexistent.  Recursing through these ugly structures can be painful especially for those unfamiliar with these structures.  I will dig through the d3 code a bit to see if we might be able to leverage some of those.  We have `data.tree` and `GeneralTree` that do well with the structure, but finding stuff is still difficult.

More than anything some visual like that in defiant.js I think is really nice.

In my life `regex` and nested querying consume quite a bit of my life and still challenge me :)

**Comment by yonicd** [comment]
A little late to the party... how about this for a solution? https://gist.github.com/yonicd/7828d9ee16b103ca3923ce94eb3f2fe6

**Comment by jennybc** [comment]
I've just come through here doing upkeep and issue triage. It's pretty clear that repurrrsive is going to be a data package, so I'm closing this as not something that's planned here.
